// <auto-generated />
namespace amardeepbazzar.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initialized : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialized));
        
        string IMigrationMetadata.Id
        {
            get { return "202106200921269_initialized"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
